//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UptonParishCouncil.Site {
    
    
    public partial class Default {
        
        /// <summary>
        /// ImageCarousel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UptonParishCouncil.Site.ImageCarousel ImageCarousel1;
        
        /// <summary>
        /// Preview1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UptonParishCouncil.Site.News.Preview Preview1;
        
        /// <summary>
        /// EventsPreview1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UptonParishCouncil.Site.Events.EventsPreview EventsPreview1;
        
        /// <summary>
        /// TwitterControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UptonParishCouncil.Site.TwitterControl TwitterControl1;
    }
}
